services:
  dev:
    build:
      image: dlbox
      ports:
        - "5000:8888"
      volumes: 
        - "/datavol/:/data/"
        - "/home/ubuntu/gov_prod/:/app:cached"
      environment: 
        - DATA_VOL=/data/