services:
  local:
    image: prod
    ports:
      - "5000:8888"
    volumes: 
      - "/home/luke/datavol/:/data/"
      - "/home/luke/repos/govhawk_ml/:/app:cached"
    runtime: nvidia
    environment: 
      - DATA_VOL=/data/
      - PYTHONPATH=/app/