jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: kciter/aws-ecr-action@master
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: 747166922306.dkr.ecr.us-east-1.amazonaws.com/govhawk_ml
        region: us-east-1
        tags: latest,${{ github.sha }}
